export enum ROBOCLOUD_ACTION {
  START = 'START',
  BUNDLE_DL_START = 'BUNDLE_DL_START',
  BUNDLE_DL_END = 'BUNDLE_DL_END',
  BUNDLE_INFO = 'BUNDLE_INFO',
  BUNDLE_UNPACK_START = 'BUNDLE_UNPACK_START',
  BUNDLE_UNPACK_END = 'BUNDLE_UNPACK_END',
  ENV_SETUP_START = 'ENV_SETUP_START',
  ENV_SETUP_END = 'ENV_SETUP_END',
  EXECUTE_END = 'EXECUTE_END',
  ARTIFACT_UL_START = 'ARTIFACT_UL_START',
  ARTIFACT_UL_END = 'ARTIFACT_UL_END',
  END = 'END',
}
