"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ROBOCLOUD_ACTION = void 0;
var ROBOCLOUD_ACTION;
(function (ROBOCLOUD_ACTION) {
    ROBOCLOUD_ACTION["START"] = "START";
    ROBOCLOUD_ACTION["BUNDLE_DL_START"] = "BUNDLE_DL_START";
    ROBOCLOUD_ACTION["BUNDLE_DL_END"] = "BUNDLE_DL_END";
    ROBOCLOUD_ACTION["BUNDLE_INFO"] = "BUNDLE_INFO";
    ROBOCLOUD_ACTION["BUNDLE_UNPACK_START"] = "BUNDLE_UNPACK_START";
    ROBOCLOUD_ACTION["BUNDLE_UNPACK_END"] = "BUNDLE_UNPACK_END";
    ROBOCLOUD_ACTION["ENV_SETUP_START"] = "ENV_SETUP_START";
    ROBOCLOUD_ACTION["ENV_SETUP_END"] = "ENV_SETUP_END";
    ROBOCLOUD_ACTION["EXECUTE_END"] = "EXECUTE_END";
    ROBOCLOUD_ACTION["ARTIFACT_UL_START"] = "ARTIFACT_UL_START";
    ROBOCLOUD_ACTION["ARTIFACT_UL_END"] = "ARTIFACT_UL_END";
    ROBOCLOUD_ACTION["END"] = "END";
})(ROBOCLOUD_ACTION = exports.ROBOCLOUD_ACTION || (exports.ROBOCLOUD_ACTION = {}));
//# sourceMappingURL=robocloud-action.js.map