channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - pip:
    - rpaframework==9.*
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
    - requests
    - datetime
    - ta-bitwarden-cli
