image: python:3.7.5

pipelines:
  default:
    - step:
        name: test
        script:
          - pip install -r requirements.txt
          - pytest
          - python -m build -s
          - python -m twine check dist/*
  branches:
    master:
      - step:
          name: test and deploy
          script:
            - pip install -r requirements.txt
            - pytest
            - python -m build -s
            - python -m twine check dist/*
            - python -m twine upload dist/*

