pipelines:
  branches:
    dev:
      - step:
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_DEV
            - export KEY_NAME=$KEY_NAME
            - nvm install 10
            - npm i
            - pipe: snyk/snyk-scan:0.2.0
              variables:
                SNYK_TOKEN: $SNYK_TOKEN
                LANGUAGE: "npm"
                DONT_BREAK_BUILD: "true"
            - npm run deploy:dev
    master:
      - step:
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_PROD
            - export KEY_NAME=$KEY_NAME
            - nvm install 10
            - npm i
            - pipe: snyk/snyk-scan:0.2.0
              variables:
                SNYK_TOKEN: $SNYK_TOKEN
                LANGUAGE: "npm"
                DONT_BREAK_BUILD: "true"
            - npm run deploy:prod
