pipelines:
  branches:
    dev:
      - step:
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_DEV
            - export BASE_URL=$BASE_URL_DEV
            - nvm install 10
            - npm i
            - pipe: snyk/snyk-scan:0.2.0
              variables:
                SNYK_TOKEN: $SNYK_TOKEN
                LANGUAGE: "npm"
                DONT_BREAK_BUILD: "true"
            - npm run build
            - apt-get update
            - apt-get install -y python3-pip 
            - pip3 install typing
            - pip3 install -U awscli
            - aws s3 rm $S3_DEV_LOCATION --recursive
            - aws s3 sync ./build $S3_DEV_LOCATION --acl public-read
            - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_DEV --paths "/*"
    master:
      - step:
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_PROD
            - export BASE_URL=$BASE_URL_PROD
            - nvm install 10
            - npm i
            - npm run build
            - apt-get update
            - apt-get install -y python3-pip
            - pip3 install typing
            - pip3 install -U awscli
            - aws s3 rm $S3_PROD_LOCATION --recursive
            - aws s3 sync ./build $S3_PROD_LOCATION --acl public-read
            - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_PROD --paths "/*"
