client_config_backend: settings
client_config:
  client_id: 973520275361-auktmvn7gqbdgc1dtapuab6qn1pudo7p.apps.googleusercontent.com
  client_secret: ivTmJvuTa5J2eoXtA3PYeLbX

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive

